name: Action Workflow

on:
  pull_request:
    branches:
      - main
  # schedule:
  #   - cron: "20 9 * * *"
  # [push, pull_request]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v1.2.0

      - name: List all modified Files
        run: |
          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            if [[ $f == *".spec.js"* ]]; then
              node ${f};
            fi
          done

      # - name: Get List of Modified and Added files
      #   uses: jitterbit/get-changed-files@v1
      #   id: changes
      #   with:
      #     format: space-delimited
      #     token: ${{ secrets.GITHUB_TOKEN }}

      # - name: Print changed files
      #   run: |
      #     for f in ${{ steps.changes.outputs.added_modified}}; do 
      #       if [[ $f == *".spec.js"* ]]; then
      #         echo "Do something with this ${f}.";
      #       fi
      #     done

      # - name: List Files
      #   run: |
      #     pwd
      #     ls -al
      #     echo $GITHUB_SHA
      #     echo $GITHUB_REPOSITORY
      #     echo $GITHUB_WORKSPACE
      #     echo "${{ github.token }}"

      # - name: Simple JS Action
      #   id: greet
      #   uses: actions/hello-world-javascript-action@v1.1
      #   with:
      #     who-to-greet: John

      # - name: Log Greeting Time
      #   run: echo "${{ steps.greet.outputs.time }}"

