name: Action Workflow

on: [push, pull_request]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
      spec: ${{ steps.changes.outputs.spec }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: Get List of Modified and Added files
        uses: jitterbit/get-changed-files@v1
        id: changes
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: echo changed files
        run: |
          echo "Added + Modified:"
          echo "${{ steps.changes.outputs.added_modified }}"
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.changes.outputs.added_modified }}')
          for added_modified_file in "${added_modified_files[@]}"; do
            echo "Do something with this ${added_modified_file}."
          done

      # - name: List Files
      #   run: |
      #     pwd
      #     ls -al
      #     echo $GITHUB_SHA
      #     echo $GITHUB_REPOSITORY
      #     echo $GITHUB_WORKSPACE
      #     echo "${{ github.token }}"

      # - name: Simple JS Action
      #   id: greet
      #   uses: actions/hello-world-javascript-action@v1.1
      #   with:
      #     who-to-greet: John

      # - name: Log Greeting Time
      #   run: echo "${{ steps.greet.outputs.time }}"
